"""Correctness tests for server/engine_worker.py's background-thread engine
loop: submission -> streamed tokens -> terminal StreamEnd, for natural
finishes, explicit aborts, and timeouts, plus concurrent requests not
cross-contaminating each other's streams.

Pure Python, no torch/CUDA -- runs the real background thread for real
(EngineWorker.start()/.stop()) against FakeEngine (server/tests/fake_engine.py),
which itself wraps the real, already-torch-free engine/scheduler.py. Reads
each StreamHandle's queue with a bounded, synchronous `queue.get(timeout=...)`
rather than the async `stream()` generator -- these tests don't run inside
an event loop; server/tests/test_app.py exercises `stream()`'s async path
via FastAPI's own request handling.
"""
import queue as queue_mod

import pytest

from engine.request import SamplingParams
from server.engine_worker import EngineWorker, StreamEnd, StreamToken
from server.tests.fake_engine import FakeEngine

DRAIN_TIMEOUT = 2.0  # generous relative to idle_poll_s so a slow CI runner can't flake this


def make_worker(idle_poll_s=0.005, default_timeout_s=60.0, cache_config=None, scheduler_config=None):
    engine = FakeEngine(cache_config, scheduler_config)
    worker = EngineWorker(engine, idle_poll_s=idle_poll_s, default_timeout_s=default_timeout_s)
    worker.start()
    return worker


def drain(handle, timeout=DRAIN_TIMEOUT):
    """Collects every item off a StreamHandle until StreamEnd, or raises if
    nothing arrives within `timeout` -- a hang here means the worker thread
    never finished the request, which is itself the failure worth surfacing
    rather than blocking pytest forever.
    """
    items = []
    while True:
        try:
            item = handle.queue.get(timeout=timeout)
        except queue_mod.Empty:
            raise AssertionError(f"no item within {timeout}s; got so far: {items}")
        items.append(item)
        if isinstance(item, StreamEnd):
            return items


@pytest.fixture
def worker():
    w = make_worker()
    yield w
    w.stop()


class TestNaturalFinish:
    def test_max_tokens_cap(self, worker):
        handle = worker.submit([1, 2, 3], SamplingParams(max_tokens=4))
        items = drain(handle)

        tokens = [i.token_id for i in items if isinstance(i, StreamToken)]
        assert tokens == [0, 1, 2, 3]  # FakeEngine's own-output-length counter
        assert items[-1] == StreamEnd(finish_reason="FINISHED_LENGTH_CAPPED")

    def test_eos_stops_early(self, worker):
        # FakeEngine's next token is len(output_token_ids) so far -- token 2
        # lands on the 3rd generated token; eos_token_id=2 should stop right there.
        handle = worker.submit([1], SamplingParams(max_tokens=10, eos_token_id=2))
        items = drain(handle)

        tokens = [i.token_id for i in items if isinstance(i, StreamToken)]
        assert tokens == [0, 1, 2]
        assert items[-1] == StreamEnd(finish_reason="FINISHED_STOPPED")

    def test_request_id_defaulted_and_returned(self, worker):
        handle = worker.submit([1], SamplingParams(max_tokens=1))
        assert handle.request_id  # non-empty, generated by submit()
        drain(handle)

    def test_explicit_request_id_honored(self, worker):
        handle = worker.submit([1], SamplingParams(max_tokens=1), request_id="my-id")
        assert handle.request_id == "my-id"
        drain(handle)


class TestAbort:
    def test_abort_stops_generation_and_frees_the_slot(self, worker):
        handle = worker.submit([1], SamplingParams(max_tokens=10_000))
        # let at least one token through so we know it was actually running
        first = handle.queue.get(timeout=DRAIN_TIMEOUT)
        assert isinstance(first, StreamToken)

        worker.abort(handle.request_id)
        items = drain(handle)
        assert items[-1] == StreamEnd(finish_reason="FINISHED_ABORTED")
        # the underlying scheduler shouldn't still be tracking it
        assert handle.request_id not in worker.engine.scheduler.requests

    def test_aborting_unknown_id_is_harmless(self, worker):
        worker.abort("no-such-request")
        # no crash, and a real request still completes normally afterwards
        handle = worker.submit([1], SamplingParams(max_tokens=1))
        drain(handle)


class TestTimeout:
    def test_default_timeout_aborts_a_stuck_request(self):
        worker = make_worker(default_timeout_s=0.05)
        try:
            handle = worker.submit([1], SamplingParams(max_tokens=10_000))
            items = drain(handle)
            assert items[-1] == StreamEnd(finish_reason="FINISHED_ABORTED")
        finally:
            worker.stop()

    def test_per_request_timeout_overrides_default(self):
        worker = make_worker(default_timeout_s=60.0)
        try:
            handle = worker.submit([1], SamplingParams(max_tokens=10_000), timeout_s=0.05)
            items = drain(handle)
            assert items[-1] == StreamEnd(finish_reason="FINISHED_ABORTED")
        finally:
            worker.stop()

    def test_timeout_none_opts_out_of_the_backstop(self):
        # default_timeout_s would fire almost immediately; a request that
        # finishes well within that window on its own proves timeout_s=None
        # was honored rather than the default silently applying anyway.
        worker = make_worker(default_timeout_s=0.02)
        try:
            handle = worker.submit([1], SamplingParams(max_tokens=3), timeout_s=None)
            items = drain(handle, timeout=1.0)
            tokens = [i.token_id for i in items if isinstance(i, StreamToken)]
            assert tokens == [0, 1, 2]
            assert items[-1] == StreamEnd(finish_reason="FINISHED_LENGTH_CAPPED")
        finally:
            worker.stop()


class TestConcurrency:
    def test_two_requests_dont_cross_contaminate(self, worker):
        h1 = worker.submit([1], SamplingParams(max_tokens=5), request_id="r1")
        h2 = worker.submit([1], SamplingParams(max_tokens=3), request_id="r2")

        items1 = drain(h1)
        items2 = drain(h2)

        tokens1 = [i.token_id for i in items1 if isinstance(i, StreamToken)]
        tokens2 = [i.token_id for i in items2 if isinstance(i, StreamToken)]
        # FakeEngine's counter is per-request (len of *its own* output list),
        # so both start at 0 independently of scheduling interleaving.
        assert tokens1 == [0, 1, 2, 3, 4]
        assert tokens2 == [0, 1, 2]
